openapi: 3.0.3
info:
  title: Student Sync API
  description: API documentation for Student Sync application
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /school:
    get:
      summary: Get all schools
      description: Fetch a list of schools with optional pagination
      parameters:
        - name: paginate
          in: query
          schema:
            type: boolean
          description: Enable pagination (default false)
        - name: page
          in: query
          schema:
            type: integer
            default: 0
          description: Page number for pagination
        - name: size
          in: query
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        "200":
          description: List of schools
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseListSchool'
    post:
      summary: Create a new school
      description: Adds a new school to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolDTO'
      responses:
        "201":
          description: School created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSchool'
  /school/{id}:
    get:
      summary: Get a school by ID
      description: Fetch details of a specific school by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: School ID
      responses:
        "200":
          description: School details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSchool'
    put:
      summary: Update a school
      description: Modify an existing school's details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: School ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolDTO'
      responses:
        "200":
          description: School updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSchool'
    delete:
      summary: Delete a school
      description: Remove a school from the system
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: School ID
      responses:
        "200":
          description: School deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    School:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        code:
          type: string
        description:
          type: string
    SchoolDTO:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        description:
          type: string
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date
    ApiResponseSchool:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/School'
    ApiResponseListSchool:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/School'
