openapi: 3.0.3
info:
  title: Student Sync API
  description: API documentation for Student Sync application
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /school:
    get:
      summary: Get all schools
      description: Retrieve a list of all schools, with optional pagination.
      parameters:
        - name: paginate
          in: query
          description: Enable pagination
          required: false
          schema:
            type: boolean
        - name: page
          in: query
          description: Page number (if pagination is enabled)
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of items per page (if pagination is enabled)
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Successfully retrieved schools
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseListSchool"

    post:
      summary: Create a new school
      description: Adds a new school to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SchoolDTO"
      responses:
        "201":
          description: School created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseSchool"

  /school/{id}:
    get:
      summary: Get a school by ID
      description: Retrieve details of a specific school using its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique school ID (UUID)
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successfully retrieved school details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseSchool"

    put:
      summary: Update a school
      description: Modify details of an existing school.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique school ID (UUID)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SchoolDTO"
      responses:
        "200":
          description: School updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseSchool"

    delete:
      summary: Delete a school
      description: Remove a school from the system.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique school ID (UUID)
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: School deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"

components:
  schemas:
    School:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string

    SchoolDTO:
      type: object
      properties:
        name:
          type: string
        address:
          type: string

    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
        data:
          type: object

    ApiResponseSchool:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/School"

    ApiResponseListSchool:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/School"

    ApiResponseVoid:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              type: "null"
