# docker-compose.yml
version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring_mvc_net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: studentSyncDB
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_mvc_net
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - spring_mvc_net

networks:
  spring_mvc_net:
    driver: bridge

volumes:
  mysql_data: